// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKHUlJthkj6-eRj15soCGnEB--mbjG99I',
    appId: '1:837949103385:web:526cb43b7d04b986633988',
    messagingSenderId: '837949103385',
    projectId: 'bookapp-8f38c',
    authDomain: 'bookapp-8f38c.firebaseapp.com',
    storageBucket: 'bookapp-8f38c.firebasestorage.app',
    measurementId: 'G-H75156DVRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDg_QSuWXA00pbuzmI_gEMHb5buQBcOA',
    appId: '1:837949103385:android:2210b4260940c216633988',
    messagingSenderId: '837949103385',
    projectId: 'bookapp-8f38c',
    storageBucket: 'bookapp-8f38c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeH7PqFCm6U-yn4qtzzGPttvLfnktDKQQ',
    appId: '1:837949103385:ios:b186179799c6be29633988',
    messagingSenderId: '837949103385',
    projectId: 'bookapp-8f38c',
    storageBucket: 'bookapp-8f38c.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeH7PqFCm6U-yn4qtzzGPttvLfnktDKQQ',
    appId: '1:837949103385:ios:b186179799c6be29633988',
    messagingSenderId: '837949103385',
    projectId: 'bookapp-8f38c',
    storageBucket: 'bookapp-8f38c.firebasestorage.app',
    iosBundleId: 'com.example.bookRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKHUlJthkj6-eRj15soCGnEB--mbjG99I',
    appId: '1:837949103385:web:e309efc2807dc7ec633988',
    messagingSenderId: '837949103385',
    projectId: 'bookapp-8f38c',
    authDomain: 'bookapp-8f38c.firebaseapp.com',
    storageBucket: 'bookapp-8f38c.firebasestorage.app',
    measurementId: 'G-2T4PK7TVWH',
  );
}
